### ISSUE TITLE
Error handling

### ISSUE THREAD

**Issue by fuzzy76** [nicegist/nicegist.github.io#22]
Right now my nicegist links takes a veeery long time to load before I'm redirected to the nicegist front page.

I'm guessing this is a github api issue. If not, you'd probably be cut off immediately with a `509 bandwidth exceeded` or something similar. Though the github status page claims everything is ok. :-/

But the actual error handling could be better. You should probably render a friendly error-message like "Gist API did not respond" when the request times out.

**Comment by eyecatchup** [comment]
Hey @fuzzy76, I can not reproduce the load time issue. But I hope [this commit](https://github.com/nicegist/nicegist.github.io/pull/23/commits/783858ff8194a134a0efce03366a48280dab7e86) will help.

I set a timeout handler for XHR requests. If they take longer than one second, I'm checking the GitHub API status to render a more helpful error message to the user.

Since I can not reproduce the issue, could you please check if that works out for you?

**Comment by eyecatchup** [comment]
Raised timeout to 1500 ms.

**Comment by fuzzy76** [comment]
Oh... The old style `/?id=` type URL causes what looks like a timeout. If I change to the new style, it works.

**Comment by fuzzy76** [comment]
Nope... Even that is wrong. I used the old address, `https://eyecatchup.github.io/nicegist/GIST_ID` so my old bookmarks stopped working. I'll update them accordingly. :)

**Comment by eyecatchup** [comment]
Ok, closing it.
