### ISSUE TITLE
Direct link to the source gist

### ISSUE THREAD

**Issue by fuzzy76** [nicegist/nicegist.github.io#8]
It would be nice if there was a link to the original gist. Perhaps in the footer?

**Comment by eyecatchup** [comment]
I've just added post metadata to the header. I guess that's the best place to add also a link to the source gist, right?

<img width="1045" alt="Bildschirmfoto 2019-03-14 um 11 01 29" src="https://user-images.githubusercontent.com/845131/54348274-fac03180-4648-11e9-9de1-e5d836f4659f.png">

--

Offtopic: I'm thinking about rendering comments, too. What do you think about it? Would that be helpful or would it rather clutter the Nicegist?

**Comment by fuzzy76** [comment]
Hmm... I'm a bit torn on that. Perhaps collapsible? And only when there actually are comments? Don't think any of my gists have comments.

**Comment by eyecatchup** [comment]
Yes, only if the gist has comments, I'd add the comment section. 

Here's an example of my local version. I'm using the same styles as the mobile gist version. I actualy like it. You can easily link to comments as well (since I'm generating comment anchor links) like so `nicegist.github.io/12345#comment-12345`

![127 0 0 1_3131__id=dab5cf7977008e504213(iPhone 6_7_8)](https://user-images.githubusercontent.com/845131/54351935-f4ce4e80-4650-11e9-8ce6-900a2f30d00f.png)

**Comment by eyecatchup** [comment]
Desktop style: 
<img width="1086" alt="Bildschirmfoto 2019-03-14 um 12 19 46" src="https://user-images.githubusercontent.com/845131/54353312-fd745400-4653-11e9-9899-ec67c6fc95b9.png">

**Comment by eyecatchup** [comment]
@fuzzy76 Closing this one, because direct link to source gist is live (link is on the pub date timestamp). Moved the discussion about comments to #10. Would be thankful for further feedback. :)
